## The two following functions generate a matrix, cache the values of that matrix
## and invert the values of the cached matrix

## makeCacheMatrix produces a square matrix x no larger than 2x2
## and stores the values of that matrix for further manipulation

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
	set <- function(y){
		x <<- y
		inv <<- NULL
	}
	get <- function() x
	
	setinverse <- function(inverse) inv <<- inverse
	getinverse <- function() inv
	list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
	
}


## cacheSolve produces the inverse of the square matrix x
## generated by makeCacheMatrix

cacheSolve <- function(x, ...) {
        inv <- x$getinverse()
    if(!is.null(inv)){
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
}
